Repository chshersh/chshersh.github.io, pull requests merged in 2022-10, with the labels that each got.

#56 Update dependencies
  .github/workflows/ci.yml
  cabal.project.freeze
  chshersh-site.cabal
Labels: enhancement, hacktoberfest-accepted

#60 Rewrite main page
  chshersh-site.cabal
  css/main-page.css
  src/Website/Main.hs
  src/Website/Project.hs
  templates/index.html
  templates/post.html
Labels: landing, hacktoberfest-accepted

#62 [#61] Add mentorship section
  src/Website/Experience.hs
  src/Website/Main.hs
  src/Website/Social.hs
  templates/index.html
Labels: landing, hacktoberfest-accepted

#65 fix matching h1 - h6 tags
  templates/index.html
Labels: landing, hacktoberfest-accepted

#67 [#66] Create signup form
  templates/index.html
Labels: landing, hacktoberfest-accepted

#68 [#63] Add 'Services' section
  posts/2022-10-20-haskell-revitalisation.md
  src/Website/Posts.hs
  templates/index.html
  templates/post.html
Labels: blog, landing

#71 [#70] Hide created date only for hidden posts
  posts/2022-10-20-haskell-revitalisation.md
  src/Website/Posts.hs
  templates/post.html
Labels: bug, hacktoberfest-accepted

#73 [#72] Mention all sections on each blog post
  src/Website/Social.hs
  templates/post.html
Labels: html/css, hacktoberfest-accepted
